name: build_windows

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
          pip install -r requirements_exe_build.txt
          python -m build --wheel

      - name: Build an executable
        shell: bash
        if: ${{ matrix.python-version == '3.12' }}
        run: |
          pip install -r requirements_exe_build.txt
          python -m build --wheel
          pyinstaller asammdf.spec --distpath dist/${RUNNER_OS} --noconfirm --clean

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/**
          if-no-files-found: error
