name: build_macos

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install packages
        run: |
            pip install build numpy wheel setuptools
            pip install -r requirements_exe_build.txt
            python setup.py bdist_wheel
            pip install -e . --no-deps
            pip install cmerg

      - name: Build an executable
        shell: bash
        if: ${{ matrix.python-version == '3.12' }}
        run: |
            pip install build numpy wheel setuptools
            pip install -r requirements_exe_build.txt
            pip install fsspec==2024.6.1
            python setup.py bdist_wheel
            pip install -e . --no-deps
            pip install cmerg
            pyinstaller asammdf.spec --distpath dist/${RUNNER_OS} --noconfirm --clean

      # see: https://docs.github.com/en/actions/advanced-guides/storing-workflow-data-as-artifacts
      - name: Archive dist artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/**
          if-no-files-found: error
